[auth]
redirect_uri = "http://platform.local:8443/oauth2callback"
cookie_secret = '5ecReT'
client_id = "platform"
client_secret = "KILUgJZ9lH3eTsAbZmoTL63ImkJJ340c"
server_metadata_url = "http://host.minikube.internal:8080/realms/Supernova/.well-known/openid-configuration"
client_kwargs = { "scopes" = "openid profile email" }
groups_token_field = 'roles'
subject_token_field = 'email'

[authZ]
admin_groups = ['linux_admins', 'domain_admins']

[mongo]
host = "host.minikube.internal"
port = 27017
username = "admin"
password = "admin"